version: "3.6"
services:
  jenkins:
    image: registry.cn-shenzhen.aliyuncs.com/nekoimi/jenkinszh:with-docker
    user: root
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-network
    volumes:
      - /home/nfs/jenkins/jenkins_home:/var/jenkins_home
      - /home/mnt/codebase:/var/codebase
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
networks:
  jenkins-network:
    driver: bridge