version: "3.6"
services:
  jenkins:
    image: registry.nekoimi.com/base-repos/jenkins:v1
    user: root
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-network
    volumes:
      - /home/nfs/jenkins/data/jenkins_home:/var/jenkins_home
      - /home/mnt/codebase:/var/codebase
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
networks:
  jenkins-network:
    driver: bridge